### ISSUE TITLE
1.2.0 - Functional upgrades

### ISSUE THREAD

**Issue by jasonrundell** [jasonrundell/partnerstack-challenge#8]
New functionality:

- [x] Add a feature that allows users to complete tasks #9 
- [x] Add a feature that allows users to delete tasks #10
- [x] Add a feature that allows the completion of all tasks #11 
- [x] Add a feature that allows the deletion of all tasks #12

Sub tasks:
- [x] Alter task model #13 
- [x] Fix npm vulnerability #14 
- [x] Package.json: Update version to 1.2.0 #16
